set -ga terminal-overrides ',xterm*:Tc:smcup@:rmcup@'
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

bind \[ if-shell "[ '#{pane_in_mode}' = '1' ]" \
"send-keys -X cancel" \
"copy-mode"

unbind -T prefix d
unbind -T prefix \"
unbind -T prefix \%

bind-key -T prefix w   choose-tree -Zs
bind-key -T prefix W   choose-tree -Zw
bind-key -T prefix c   new-window -c "#{pane_current_path}"
bind-key -T prefix C   new-window
bind-key -T prefix v   split-pane -h -c "#{pane_current_path}"
bind-key -T prefix V   split-pane -h
bind-key -T prefix s   split-pane -v -c "#{pane_current_path}"
bind-key -T prefix S   split-pane -v
bind-key -T prefix \+  setw synchronize-panes
bind-key -T prefix C-s command-prompt -p "Swap with pane:" "swap-pane -t '%%'"
bind-key -T prefix C-l send-keys C-l \; clear-history
bind-key -T prefix C-r source-file ~/.config/tmux/tmux.conf \; display "Reloaded configurations"

bind-key -T root C-Up     select-pane -U
bind-key -T root C-Down   select-pane -D
bind-key -T root C-Left   select-pane -L
bind-key -T root C-Right  select-pane -R
bind-key -T root C-PageUp if-shell "'#{pane_in_mode}'" \
"send-keys -X -N 5 scroll-up" \
"copy-mode; send-keys -X -N 5 scroll-up"

bind-key -T root C-PageDown if-shell "'#{pane_in_mode}'" \
"send-keys -X -N 5 scroll-down" \
"copy-mode; send-keys -X -N 5 scroll-down"

bind-key -T copy-mode-vi y send-keys -X copy-pipe
bind-key -T copy-mode-vi v send-keys -X begin-selection
