set -ga terminal-overrides ',xterm*:Tc:smcup@:rmcup@'
set -g display-time 4000
set -g repeat-time 0

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-interval 5
set -g status-keys emacs
set -g status on

# style configurations
set -g mode-style                    'bg=colour7,fg=colour8' 
set -g status-style                  'bg=colour0,fg=colour7'
set -g status-left                   ''
set -g status-right                  '#{?window_zoomed_flag,[+],}'
set -g window-status-format          ''
set -g window-status-current-format  ''
set -g pane-border-style             "#{?pane_synchronized,fg=colour1,fg=colour8}"
set -g pane-active-border-style      "#{?pane_synchronized,fg=colour1,fg=colour8}"
set -g cursor-style                  'block'
set -g cursor-colour                 default
set -g prompt-cursor-colour          default
set -g message-style                 'bg=colour0,fg=colour7'
set -g message-command-style         'bg=colour0,fg=colour7'
set -g window-status-current-style   'fg=colour0,bg=colour7'
set -g copy-mode-match-style         'fg=colour0,bg=colour7'
set -g copy-mode-current-match-style 'fg=colour0,bg=colour3'
set -g copy-mode-selection-style     'fg=default,bg=colour8'

# keybind configurations

bind \[ if-shell "[ '#{pane_in_mode}' = '1' ]" "send-keys -X cancel" "copy-mode"

unbind -T prefix d
unbind -T prefix \"
unbind -T prefix \%

bind-key -T prefix w     choose-tree -Zs
bind-key -T prefix W     choose-tree -Zw
bind-key -T prefix c     new-window -c "#{pane_current_path}"
bind-key -T prefix C     new-window
bind-key -T prefix v     split-pane -h -c "#{pane_current_path}"
bind-key -T prefix V     split-pane -h
bind-key -T prefix s     split-pane -v -c "#{pane_current_path}"
bind-key -T prefix S     split-pane -v
bind-key -T prefix \+    setw synchronize-panes
bind-key -T prefix /     copy-mode \; send-key / 
bind-key -T prefix C-s   command-prompt -p "Swap with pane:" "swap-pane -t '%%'"
bind-key -T prefix C-l   send-keys C-l \; clear-history
bind-key -T prefix C-r   source-file ~/.config/tmux/tmux.conf \; display "Reloaded configurations"
bind-key -T prefix Up    if-shell "[ '#{pane_at_top}' = '0' ]" "select-pane -U"
bind-key -T prefix Down  if-shell "[ '#{pane_at_bottom}' = '0' ]" "select-pane -D"
bind-key -T prefix Left  if-shell "[ '#{pane_at_left}' = '0' ]" "select-pane -L"
bind-key -T prefix Right if-shell "[ '#{pane_at_right}' = '0' ]" "select-pane -R"
bind-key -T prefix ?     display-panes -d 0 "swap-pane -s '%%'"

bind-key -T root C-PageUp if-shell "#{pane_in_mode}" \
  "send-keys -X -N 5 scroll-up" \
  "copy-mode; send-keys -X -N 5 scroll-up"

bind-key -T root C-PageDown if-shell "#{pane_in_mode}" \
  "send-keys -X -N 5 scroll-down" \
  "copy-mode; send-keys -X -N 5 scroll-down"


unbind -T copy-mode-vi q 
unbind -T copy-mode-vi C-c
unbind -T copy-mode-vi M-x
unbind -T copy-mode    M-x

bind-key -T copy-mode    C-o send-keys -X jump-to-mark
bind-key -T copy-mode-vi C-o send-keys -X jump-to-mark
bind-key -T copy-mode    C-g send-keys -X cancel
bind-key -T copy-mode-vi w   send-keys -X select-word
bind-key -T copy-mode-vi C-g send-keys -X clear-selection
bind-key -T copy-mode-vi y   send-keys -X copy-pipe
bind-key -T copy-mode-vi v   send-keys -X begin-selection
